In [8]:
import django_initializer
from telemetry.fast_lap_analyzer import FastLapAnalyzer
from telemetry.racing_stats import RacingStats
from telemetry.models import FastLap, Lap
from telemetry.analyzer import Analyzer
from telemetry.influx import Influx
import plotly.io as pio

# pio.renderers.default = "svg"  # comment this line to use interactive plots

import pandas as pd
import numpy as np

from telemetry.visualizer import *

%load_ext autoreload
%autoreload 2

analyzer = Analyzer()
influx = Influx()
fast_lap_analyzer = FastLapAnalyzer()
fast_lap_analyzer.columns += ['WorldPosition_x', 'WorldPosition_y', 'WorldPosition_z']
racing_stats = RacingStats()

2023-12-30 21:27:58,812 DEBUG Influx: Connected to https://telemetry.b4mad.racing:443/


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
kwargs = {
    "game__name": "Richard Burns Rally",
    "track__name": "East-West",
    "car__name": "Mitsubishi Lancer Evo X R4",
}
lap_id = 696976
laps = []
if lap_id:
    lap = Lap.objects.get(pk=lap_id)
    laps.append(lap)
else:
    laps = racing_stats.laps(**kwargs)
    laps = laps[:10]
# laps = list(laps)
fast_lap_analyzer.laps = laps
data_frames, laps_with_telemetry = fast_lap_analyzer.fetch_lap_telemetry()

2023-12-30 21:28:01,465 DEBUG Influx: Connected to https://telemetry.b4mad.racing:443/
2023-12-30 21:28:01,629 INFO Fetching telemetry for Richard Burns Rally - East-West - Mitsubishi Lancer Evo X R4
2023-12-30 21:28:01,630 INFO   track.id 3262 car.id 4034
2023-12-30 21:28:01,630 INFO   session 1703765558 lap.id 696976 number 0
2023-12-30 21:28:01,630 INFO   length 9908 time 519.9802 valid True
2023-12-30 21:28:01,631 INFO   start 2023-12-28 13:12:38.380911+00:00 end 2023-12-28 13:22:18.361111+00:00
2023-12-30 21:28:01,817 ERROR No data found for 1703765558 lap 0
2023-12-30 21:28:01,818 INFO No data found for lap in fast_laps bucket, trying in default bucket
2023-12-30 21:28:01,818 INFO Fetching telemetry for Richard Burns Rally - East-West - Mitsubishi Lancer Evo X R4
2023-12-30 21:28:01,819 INFO   track.id 3262 car.id 4034
2023-12-30 21:28:01,819 INFO   session 1703765558 lap.id 696976 number 0
2023-12-30 21:28:01,819 INFO   length 9908 time 519.9802 valid True
2023-12-30 21:28:01,81

In [22]:
df = data_frames[0].copy()
# get all distinct values of column 'WorldPosition_x' in dataframe
display(df["WorldPosition_x"].unique())
# get all distinct values of column 'WorldPosition_y' in dataframe
display(df["WorldPosition_y"].unique())
# get all distinct values of column 'WorldPosition_z' in dataframe
display(df["WorldPosition_z"].unique())

display(df)
f = go.FigureWidget()
display(f)




f.add_scatter(
    x=df["WorldPosition_x"],
    y=df["WorldPosition_y"],
    mode="markers",
    marker=dict(size=2),
)

    # plt.figure()
    # x = points_a[idx][:,0]
    # y = points_a[idx][:,1]
    # plt.scatter(x, y, s=0.1)
    # plt.gca().set_aspect('equal', 'datalim')
    # plt.xlabel('WorldPosition_x')
    # plt.ylabel('WorldPosition_z')
    # plt.show()

array([-4.7572945e-38])

array([1.14438769e-28])

array([1.14438769e-28])

DistanceRoundTrack     Brake    SpeedMs  Throttle  Gear  CurrentLapTime  \
0                 134.00  0.000000  12.396770       1.0   2.0        0.298611   
1                 134.99  0.000000  14.079876       1.0   2.0        0.622222   
2                 135.97  0.000000  14.303643       1.0   2.0        0.736111   
3                 136.96  0.000000  14.575289       1.0   2.0        0.962501   
4                 137.95  0.000000  14.561991       1.0   2.0        1.073612   
...                  ...       ...        ...       ...   ...             ...   
9915             9916.05  0.650980   5.353969       0.0   1.0      519.980200   
9916             9917.04  0.650980   4.470027       0.0   1.0      519.980200   
9917             9918.03  0.650980   3.989217       0.0   1.0      519.980200   
9918             9919.01  0.647059   3.571800       0.0   1.0      519.980200   
9919             9920.00  0.643137   2.637594       0.0   1.0      519.980200   

      SteeringAngle                 Time  WorldPosition_x  WorldPosition_y  \
0          0.000000  1703769188784505088    -4.757294e-38     1.144388e-28   
1          0.000000  1703769189108282112    -4.757294e-38     1.144388e-28   
2          0.000000  1703769189216407040    -4.757294e-38     1.144388e-28   
3          0.000000  1703769189447545088    -4.757294e-38     1.144388e-28   
4          0.000000  1703769189555398912    -4.757294e-38     1.144388e-28   
...             ...                  ...              ...              ...   
9915      -0.235294  1703769673699815936    -4.757294e-38     1.144388e-28   
9916      -0.196078  1703769673915834880    -4.757294e-38     1.144388e-28   
9917      -0.172549  1703769674025970944    -4.757294e-38     1.144388e-28   
9918      -0.156863  1703769674129639936    -4.757294e-38     1.144388e-28   
9919      -0.149020  1703769674348169984    -4.757294e-38     1.144388e-28   

      WorldPosition_z  
0        1.144388e-28  
1        1.144388e-28  
2        1.144388e-28  
3        1.144388e-28  
4        1.144388e-28  
...               ...  
9915     1.144388e-28  
9916     1.144388e-28  
9917     1.144388e-28  
9918     1.144388e-28  
9919     1.144388e-28  

[9920 rows x 11 columns]

FigureWidget({
    'data': [], 'layout': {'template': '...'}
})

FigureWidget({
    'data': [{'marker': {'size': 2},
              'mode': 'markers',
              'type': 'scatter',
              'uid': '7500b8d2-df3f-4989-8f23-14608302e64a',
              'x': array([-4.7572945e-38, -4.7572945e-38, -4.7572945e-38, ..., -4.7572945e-38,
                          -4.7572945e-38, -4.7572945e-38]),
              'y': array([1.14438769e-28, 1.14438769e-28, 1.14438769e-28, ..., 1.14438769e-28,
                          1.14438769e-28, 1.14438769e-28])}],
    'layout': {'template': '...'}
})

2023-12-30 21:40:46,495 DEBUG handle_msg[aa0da1f53535474984b30191de06c3a1]({'header': {'date': datetime.datetime(2023, 12, 30, 21, 40, 46, 482000, tzinfo=tzlocal()), 'msg_id': '1f98ab4d-c581-40f0-8d7a-a623c8b515f7', 'msg_type': 'comm_msg', 'session': 'e75e89e2-a809-4ed1-8efb-fff1cba35a67', 'username': 'f3fd61db-b2ca-4fd7-a080-5332dfcf7b69', 'version': '5.2'}, 'msg_id': '1f98ab4d-c581-40f0-8d7a-a623c8b515f7', 'msg_type': 'comm_msg', 'parent_header': {}, 'metadata': {}, 'content': {'comm_id': 'aa0da1f53535474984b30191de06c3a1', 'data': {'method': 'update', 'state': {'_view_count': 1}, 'buffer_paths': []}}, 'buffers': []})
2023-12-30 21:40:46,896 DEBUG handle_msg[aa0da1f53535474984b30191de06c3a1]({'header': {'date': datetime.datetime(2023, 12, 30, 21, 40, 46, 894000, tzinfo=tzlocal()), 'msg_id': '8562ca86-3311-4684-9671-8ffca89ed157', 'msg_type': 'comm_msg', 'session': 'e75e89e2-a809-4ed1-8efb-fff1cba35a67', 'username': 'f3fd61db-b2ca-4fd7-a080-5332dfcf7b69', 'version': '5.2'}, 'msg_id': 